### PR TITLE
zh-Hans for Q.O.L. 3000

### PR DESCRIPTION
**Pull request by URARUA**
Complete zh-Hans translation for Q.O.L. 3000

### CODE REVIEW

**Comment by URARUA** [comment]
7821b27 should not be contained in PR, but blame VSCode
i'm too lazy to revert this :D

**Review by BlockCrusader — COMMENTED** [review]
Thanks for the localization! I noticed you missed a few things like the config display names and headers, one of the config setting names, and Sandstorm Slab's name, just in case you has meant to add localization for those.
I'm going to release a small update soon that adds a couple new config. settings so for the moment I'm gonna delay on merging, so that you can localize those additions as needed before I add the localization to the mod.
Oh, and no worries about the .gitignore thing.

**Comment by BlockCrusader** [comment]
Update is now out on Steam Workshop; you should now be able to see the new config. settings for localizing.

**Comment by URARUA** [comment]
> Thanks for the localization! I noticed you missed a few things like the config display names and headers, one of the config setting names, and Sandstorm Slab's name, just in case you has meant to add localization for those. I'm going to release a small update soon that adds a couple new config. settings so for the moment I'm gonna delay on merging, so that you can localize those additions as needed before I add the localization to the mod. Oh, and no worries about the .gitignore thing.

missing translation should be added now

**Review by URARUA — COMMENTED** [review]
translation done

**Review by BlockCrusader — APPROVED** [review]

**Pull request merged**
